USE TESTETECNICODB;

CREATE TABLE `TB_USER` (
	`ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`LOGIN` VARCHAR(20) NOT NULL,
	`PASSWORD` VARCHAR(50) NOT NULL,
	`EMAIL` VARCHAR(100) NULL,
	PRIMARY KEY (`ID`)
)
COLLATE='utf8_unicode_ci'
ENGINE=InnoDB
;

INSERT INTO TB_USER (`LOGIN`, `PASSWORD`, `EMAIL`) VALUES ('admin','admin123','admin@testetecnico.com');
INSERT INTO TB_USER (`LOGIN`, `PASSWORD`, `EMAIL`) VALUES ('rcarriel','admin123','rubens.carriel@gmail.com');