version: 0.0
os: linux
hooks:
  BeforeInstall:
    - location: docker/scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: docker/scripts/stop_server
      timeout: 300
      runas: root
