version: '3.3'
networks: 
  banco:
  web:
services:
  db:
    image: mysql:8.0
    build:
      context: ./Database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'r00t'
    ports:
      - '3306:3306'
    volumes:
      - ./containers/db:/var/lib/mysql
    networks: 
      - banco
  front:
    image: node:12.2.0-alpine
    build:
      context: ./FrontendReact
    ports:
      - 3000:3000
    command: npm start
    networks: 
      - web
    depends_on: 
      - app
  app:
    image: 'mcr.microsoft.com/dotnet/core/aspnet:2.2-stretch-slim'
    build:
      context: ./BackendApi/BackendApi
    ports:
      - 8080:80
      - 3443:443
    networks: 
      - banco
      - web
    depends_on: 
      - db