version: '3.3'
networks: 
  banco:
  web:
services:
  db:
    container_name: mysql
    image: testetecnico/mysql
    build:
      context: ../Database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'r00t'
    ports:
      - '3306:3306'
    networks: 
      - banco
  front:
    container_name: nginx
    image: testetecnico/nginx
    build:
      context: ../FrontendReact
    restart: always
    ports:
      - 80:80
    networks: 
      - web
    depends_on: 
      - app
  app:
    container_name: api
    image: testetecnico/api-netcore
    build:
      context: ../BackendApi/BackendApi
    restart: always
    ports:
      - 8080:80
      - 3443:443
    networks: 
      - banco
      - web
    depends_on: 
      - db