version: '3.3'
networks: 
  banco:
  web:
services:
  db:
    image: mysql:8.0
    build:
      context: ../Database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'r00t'
    ports:
      - '3306:3306'
    networks: 
      - banco
  front:
    image: node:12.2.0-alpine
    build:
      context: ../FrontendReact
    restart: always
    ports:
      - 80:80
    networks: 
      - web
    depends_on: 
      - app
  app:
    image: 'mcr.microsoft.com/dotnet/core/aspnet:2.2-stretch-slim'
    build:
      context: ../BackendApi/BackendApi
    restart: always
    ports:
      - 8080:80
      - 3443:443
    networks: 
      - banco
      - web
    depends_on: 
      - db