version: '3'
volumes:
  dados:
networks: 
  banco:
  web:
services:
  db:
    image: 'microsoft/mssql-server-linux:2017-latest'
    environment:
      MSSQL_SA_PASSWORD: 'DockerSql2017!'
      MSSQL_PID: 'Developer'
      ACCEPT_EULA: 'Y'
    ports:
      - 1433:1433
#    volumes:
#      - 'D:\SQLServer2017:/var/opt/mssql'
  front:
    image: nginx:1.13
    volumes: 
      - ./web:/usr/share/nginx/html/
    ports:
      - 80:80
    networks: 
      - web
    depends_on: 
      - app
  app:
    image: ""
    ports:
      - 8080:80
    networks: 
      - banco
      - web
    depends_on: 
      - db
